### ISSUE TITLE
Read config from other places

### ISSUE THREAD

**Issue by VincentSurelle** [mbrehin/git-precommit-checks#43]
Hi,

That would be great if your project could read from other places than package.json.

I'm using [Rush](https://rushjs.io) and I don't have root package.json file.

Maybe a `.precommit-check.json` or something similar would be good ?

**Comment by mbrehin** [comment]
Hey there,

I just updated the project to allow external configuration file `git-precommit-checks.json` to be used instead of `package.json`.

`package.json` will stil be used as a fallback when no previous configuration is found.

**Comment by VincentSurelle** [comment]
Just wow ! In less than three hours having the feature asked is great !

Thanks a lot !

**Comment by mbrehin** [comment]
You're welcome! I pushed further and released v3.0.0 that allows JS configuration (which is a better format, easier to user…). 

That's a breaking change due to configuration keys that have been renamed (some were still using kebab-case instead of camelCase).

Here's the release note: https://github.com/mbrehin/git-precommit-checks/releases/tag/v3.0.0

**Comment by VincentSurelle** [comment]
Great thank you !

**Comment by VincentSurelle** [comment]
Looks like `.js` file is not recognized.

But it works with `.json` file

**Comment by VincentSurelle** [comment]
Looks like `.js` file is not recognized.

But it works with `.json` file

**Comment by mbrehin** [comment]
You have to upgrade to v3.0.0 is you want to use `.config.js` file. If you already did, I’d be interested in your feedback (error message, context etc.).
