### ISSUE TITLE
Rule with  "nonBlocking": "false"

### ISSUE THREAD

**Issue by gdo** [mbrehin/git-precommit-checks#49]
Hello,

The following rule : 
      {
        "filter": "\\.js$",
        "message": "You’ve got leftover `console.log`",
        "regex": "console\\.log",
        "nonBlocking": "**false**"
      }
Create the commit. I must remove attribut "nonBlocking" to forbid the creation of the commit.

**Comment by mbrehin** [comment]
Hi @gdo, 

Can you tell me which git-precommit-checks version you're using? 

The first problem that appears to me is that you’re not "double escaping" the dots in your `filter` and `regex` rules. This has to be done if you are using the `package.json` config. Otherwise you can switch to the external js conf as explained in the docs.

I've tested your conf with the `nonBlocking` set to `false` and everthing works just fine.

Maybe you can try to upgrade to the latest version or you can give me more detail about the problem you encountered so I could give you a better answer.

Regards
